.pragma library
var details={
"Brightness / scale":"Backlight brightness as a percentage of the driver's maximum; display scale is KDE's logical scaling factor. Neither is refresh rate.",
"CPU policy":"Energy-performance preference and CPU boost setting, reported by the CPU frequency driver.",
"Uptime":"Time since the current system boot, including time counted by the operating system during suspend.",
"CPU core power":"Power used by CPU cores according to AMD firmware. Already included within chip power, not additional wall consumption.",
"Frequency policy range":"Configured CPU minimum and maximum clock frequencies. Actual frequencies vary with workload and firmware limits.",
"Load average · 1 / 5 / 15 min":"Average runnable or uninterruptible tasks over 1, 5 and 15 minutes. These are task counts, not CPU utilization percentages.",
"DRAM read / write":"Firmware-reported read and write traffic to main memory, in megabytes per second.",
"Device / runtime power state":"NPU device name and runtime power-management state. Suspended does not by itself establish a utilization percentage.",
"Firmware column activity":"Activity reported by individual NPU/IPU columns. Each percentage refers to its own firmware column.",
"Power / clock":"NPU domain power in watts and operating frequency in MHz, reported by AMD firmware.",
"NPU read / write":"Firmware-reported NPU memory traffic in megabytes per second.",
"Available / cache":"Linux memory available for applications and page cache, respectively. Cache can often be reclaimed and is not necessarily pressure.",
"Swap used / total":"Allocated swap space and configured swap capacity. Swap is not extra physical RAM.",
"Detected source":"Active battery, ASUS barrel or USB-C source. Any displayed charger watt rating is owner-configured nameplate capacity, not measured draw.",
"Suggested profile":"A suggestion based on the detected power source; the widget never automatically applies it.",
"USB-C negotiated contract":"Selected UCSI voltage multiplied by operating current. This is the negotiated contract, not real-time wall consumption.",
"Power profiles daemon":"Current profile reported by power-profiles-daemon. Use the header buttons to request a change.",
"Firmware platform profile":"Platform profile exposed by firmware. It can differ from the desktop's requested profile.",
"CPU driver / governor":"CPU frequency driver and governor currently controlling scheduling/frequency policy.",
"Energy performance preference":"CPU driver's preference between energy efficiency and performance. It is not a measured wattage.",
"CPU boost":"Whether the CPU driver allows boost frequencies. Enabled does not mean the CPU is constantly boosting.",
"GPU performance policy":"amdgpu performance policy, such as auto. Actual clock and power still depend on load.",
"STAPM limit / current":"Firmware-reported sustained thermal-aware power limits, when available. Unknown/sentinel readings remain unavailable.",
"Battery state":"Status reported by the battery driver: charging, discharging, full, or not charging.",
"Instantaneous battery flow":"Battery power flow in watts. Interpret direction using the charging/discharging state; this is different from APU power.",
"Smoothed flow · 30 s":"Battery flow smoothed with a 30-second exponential time constant, used for remaining-time estimates.",
"Remaining / full energy":"Energy currently stored and learned full-charge capacity, in watt-hours.",
"Design capacity / health":"Nameplate energy capacity and learned full-charge capacity as a percentage of design. Reported health may slightly exceed 100%.",
"Voltage / cycles":"Battery voltage and driver-reported charge-cycle count. A missing cycle count is not zero.",
"Charge limit":"Configured battery charge ceiling reported by the driver. This widget does not change it."
}
function explain(label){return details[label] || (label.indexOf('ppt_')===0?"Raw ASUS firmware control readback. It is not a measured wattage or a reliable enforced power limit.":"Driver-reported "+label.toLowerCase()+". A dash means the source did not provide a supported reading.")}
